version = 0.1

[dev.deploy.parameters]
stack_name = "wumbo-core-dev"
resolve_s3 = true
s3_prefix = "wumbo-core-dev"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = """\
ServiceName="wumbo-core" \
EnvironmentName="dev" \
VpcId="vpc-062ae6a609870fe32" \
VpcCidr="10.20.0.0/16" \
PrivateSubnetIds="subnet-0be082725b4b8d5c7,subnet-01bc92cc78884c77f" \
DatabaseHost="wumbo-marketplace-dev-postgres.c5844q4ui74l.us-west-2.rds.amazonaws.com" \
DatabasePort="5432" \
DatabaseName="marketplace" \
DatabaseUsername="wumbo_marketplace" \
DatabaseSecretArn="arn:aws:secretsmanager:us-west-2:498309140969:secret:wumbo-marketplace-dev-postgres/master-password-8ckW4o" \
DatabaseSecretKmsKeyArn="arn:aws:kms:us-west-2:498309140969:key/6d268ac7-1d64-47d2-915d-ac7ad2e4b574" \
EventBusName="wumbo-marketplace-dev-domain-events" \
CognitoIssuer="https://cognito-idp.us-west-2.amazonaws.com/us-west-2_4sjDZ63PZ" \
CognitoAudiences="32h0ar20p1nnmc1t006fl7m370,7g75moc3nhun520scig46j9hk9" \
StandardAlertsTopicArn="arn:aws:sns:us-west-2:498309140969:wumbo-marketplace-dev-alerts-standard" \
CriticalAlertsTopicArn="arn:aws:sns:us-west-2:498309140969:wumbo-marketplace-dev-alerts-critical" \
PublisherScheduleExpression="rate(1 minute)" \
PublisherScheduleState="ENABLED" \
PublisherBatchSize="10"\
"""
image_repositories = []

[dev.global.parameters]
region = "us-west-2"
